# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[aws]
symbol = "AWS "

[gcloud]
symbol = "GCP "

[directory]
truncation_length = 10
truncate_to_repo = false
fish_style_pwd_dir_length = 1
