# Default data value for templating
name = "Kien Truong"
email = "duckientruong@gmail.com"
mergetool = "kdiff3"

python_site_package_dirs = [
    "/usr/lib/python3/dist-packages",
    "/usr/lib/python3.10/site-packages",
    "/usr/lib/python3.11/site-packages"
]

python_copier_repo = "https://github.com/kien-truong/python-copier.git"

strong_gpu = true

wayland = true

systemd_enabled = true
