[".vim/pack/themes/opt/solarized8"]
    type = "git-repo"
    url = "https://github.com/lifepillar/vim-solarized8.git"
    refreshPeriod = "168h"

[".zprezto_ext/zfunc/conda-zsh-completion"]
    type = "git-repo"
    url = "https://github.com/conda-incubator/conda-zsh-completion.git"
    refreshPeriod = "168h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-continuum"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-continuum.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-resurrect"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-resurrect.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-sensible"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-sensible.git"
    refreshPeriod = "168h"

[".tmux/plugins/tmux-yank"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tmux-yank.git"
    refreshPeriod = "168h"

[".zprezto_ext/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
    refreshPeriod = "168h"
