[window]
decorations = "none"

[cursor]
style = { shape = "Beam", blinking = "Always" }
blink_timeout = 0
blink_interval = 500

[font]
normal = { family = "CaskaydiaCove NFP", style = "SemiLight" }
bold = { style = "SemiBold" }
italic = { style = "SemiLight Italic" }
bold_italic = { style = "SemiBold Italic" }
